modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="researchtree"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="researchtree.mixins.json"

[[dependencies.researchtree]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"